imports:
  - python

filter:
  excluded_paths:
    - "database/"

build:
  nodes:
    my-tests:
      environment:
        python: "3.10"

      # Run tests and analysis tools
      analysis:
        project_setup:
          override: true # Set to true without quotes

      # Run test scripts
      tests:
        override:
          # Command to run Python's built-in unittest
          - command: "python -m unittest discover -s tests" # Adjust 'tests' to your test directory


          # Command to run Pylint (for code linting)
          # - command: "pylint . --disable=R,C" # Adjust based on your linting preferences
