imports:
  - python

filter:
  excluded_paths:
    - "database/"

build:
  nodes:
    my-tests:
      environment:
        python: "3.10" # Specify Python version

      # Project setup step (optional, based on your needs)
      project_setup:
        override: true

      # Specify the commands or scripts to run
      commands:
        - command: "python -m unittest discover -s tests" # Discover and run unittests
        # - command: "pylint . --disable=R,C" # Run pylint for linting the codebase
