imports:
  - python

filter:
  excluded_paths:
    - "database/"

build:
  nodes:
    my-tests:
      environment:
        python: "3.7.1"

      # Use the commands key for all setup and test commands
      commands:
        # Command to run Python's built-in unittest
        - command: "python -m unittest discover -s tests"

        # Command to run Pylint for linting the codebase
        - command: "pylint . --disable=R,C"
